a="12345"
print(a.isupper())
print(a.islower())
print(a.isalpha())
print(a.isalnum())
print(a.isdigit())
print(a.isspace())
print(a.istitle())
print(a.startswith('4'))
print(a.endswith('6'))
print(a.find("5"))
print(len(a))
print(min(a))
print(max(a))

